name: File List

on: [push]

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout DotMod Repo
      uses: actions/checkout@v2
      with:
        path: dotmod
    - name: Checkout DMG Website Repo
      uses: actions/checkout@v2
      with:
        repository: DotModGroup/DotModGroup.github.io
        path: website
    - name : Write Data
      run: |
        cd website
        date > generated.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: website
