name: File List
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DotMod Repo
        uses: actions/checkout@v2
        with:
          path: main
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
      - name: Checkout DotMod Website Repo
        uses:  actions/checkout@v2
        with:
          path: website
          repository: DotModGroup/DotModGroup.github.io
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
      - name: Build Weapon Data Table
        shell: pwsh
        run: |
          ./main/.github/scripts/buildWeaponDataTable.ps1
      - name: Commit Website Repo Changes
        run: |
          cd website
          date > lastupdate.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
