name: File List
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: website
          repository: DotModGroup/DotModGroup.github.io
          token: ${{ secrets.ORG_ACCESS_TOKEN }}
      - run: |
          cd website
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
