name: File List

on: [push]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.ORG_ACCESS_TOKEN }}
        src_path: ColdWaters_Data/StreamingAssets/dotmod/hud/sprites/
        dst_path: /resources/images/
        dst_owner: DotModGroup
        dst_repo_name: DotModGroup.github.io
